- title: Identifi
  description: "When we acquired this business it’s product had been in the part for over 5 years and had served thousands of customers across Asia improve the way they managed employee performance. We are now in the process of rebuilding the software from the ground up to cater to a wider audience and enable businesses of all sizes to dramatically improve how they interface with their most important asset, *their people*."
  cta: "Check out Identifi"
  icon: https:icon.now.sh/vpn_key/4A9547

- title: OneInbox
  description: "The number of channels customers are engaging with businesses is rapidly increasing. Keeping track of conversations and knowing what was said on one channel when replying in another is becoming very difficult to manage. OneInbox simplifies that problem by aggregating all the channels into one spot giving customers a single interface to respond and manage relationships with all their customers."
  cta: "Check out OneInbox"
  icon: https:icon.now.sh/mail_outline